---
AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Resources:

  CreateQuote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: cmd/create-quote
      Runtime: go1.x
      Events:
        CreateEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
        ImportEvent:
          Type: Api
          Properties:
            Path: /import
            Method: post

  ReadQuote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: cmd/read-quote
      Runtime: go1.x
      Events:
        ListEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
        GetEvent:
          Type: Api
          Properties:
            Path: /{id}
            Method: get

  UpdateQuote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: cmd/update-quote
      Runtime: go1.x
      Events:
        UpdateEvent:
          Type: Api
          Properties:
            Path: /{id}
            Method: put

  DeleteQuote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: cmd/delete-quote
      Runtime: go1.x
      Events:
        DeleteEvent:
          Type: Api
          Properties:
            Path: /{id}
            Method: delete

Outputs:

  Endpoint:
    Value:  !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/staging/quotes"