---
AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Resources:

  CreateQuote:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: cmd/create-quote
      Runtime: go1.x
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post

  ReadQuotes:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: cmd/read-quotes
      Runtime: go1.x
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get

Outputs:

  Endpoint:
    Value:  !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/staging/quotes"